name: Concatenate Markdown Files

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Concatenate Markdown files
        run: node concatenate-md.js

      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit -m "Update concatenated Markdown file" -a || echo "No changes to commit"
          git push